name: dereplicate
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - bowtie2=2.5.1
  - coverm=0.6.1
  - csvkit=1.3.0
  - dram=1.4.6
  - parallel=20230922
  - quast=5.2.0
  - r-argparse=2.2.2
  - r-tidyverse=2.0.0
  - samtools=1.18
