mag_annotate__bakta: medium,large,highmem,longrun,highmem_longrun
mag_annotate__bakta_mags_run: medium,large,highmem,longrun,highmem_longrun
mag_annotate__camper__annotate: medium,large,highmem,longrun,highmem_longrun
mag_annotate__checkm2__predict: medium,large,highmem,longrun,highmem_longrun
mag_annotate__dram__annotate: large,highmem,longrun,highmem_longrun
mag_annotate__dram__distill: small, medium, large
mag_annotate__dram_mag__annotate: large,highmem,longrun,highmem_longrun
mag_annotate__eggnog: large,highmem,longrun,highmem_longrun
mag_annotate__fix_dram_mag_annotations_scaffold: small, medium, large
mag_annotate__gtdbtk__classify: large,highmem,longrun,highmem_longrun
mag_annotate__phylophlan: medium,large
mag_annotate__proteinortho: medium,large
mag_annotate__quast: medium,large

assemble__bowtie2__build: medium,large,highmem,longrun,highmem_longrun
assemble__bowtie2__map: medium,large,highmem,longrun,highmem_longrun
assemble__concoct_run: large,highmem,longrun,highmem_longrun
assemble__drep__join_genomes: medium,large
assemble__drep__run: medium,large,highmem,longrun,highmem_longrun
assemble__drep__separate_bins: small, medium, large
assemble__magscot__prodigal: medium,large,highmem,longrun,highmem_longrun
assemble__magscot__hmmsearch_pfam: medium,large,highmem,longrun,highmem_longrun
assemble__magscot__hmmsearch_tigr: medium,large,highmem,longrun,highmem_longrun
assemble__magscot__join_hmms: small,medium,large,highmem,longrun,highmem_longrun
assemble__magscot__merge_contig_to_bin: small,medium,large,highmem,longrun,highmem_longrun
assemble__magscot__run: small,medium,large,highmem,longrun,highmem_longrun
assemble__magscot__reformat: small,medium,large,highmem,longrun,highmem_longrun
assemble__magscot__rename: small,medium,large,highmem,longrun,highmem_longrun
assemble__maxbin2__run: large,highmem,longrun,highmem_longrun
assemble__metabat2__run: large,highmem,longrun,highmem_longrun
assemble__megahit__run: large,highmem,longrun,highmem_longrun
assemble__metaspades__run: large,highmem,longrun,highmem_longrun

contig_annotate__camper__annotate: medium,large
contig_annotate__eggnog_find_homology: medium,large,highmem,longrun,highmem_longrun
contig_annotate__eggnog_orthology: large,highmem,longrun,highmem_longrun
contig_annotate__cramToBam: small, medium, large
contig_annotate__featurecounts_run: medium,large
contig_annotate__prodigal_run: medium,large,highmem,longrun,highmem_longrun
contig_annotate__cut_prodigal: medium,large,highmem,longrun,highmem_longrun

helpers__fastqc: small, medium, large
helpers__samtools__faidx_fa: small,medium,large
helpers__samtools__faidx_fagz: small,medium,large
helpers__samtools__flagstats_cram: small,medium,large
helpers__samtools__idxstats_cram: small,medium,large
helpers__samtools__index_bam: medium,large
helpers__samtools__index_cram: small,medium,large

preprocess__bowtie2__build: medium,large,highmem,longrun,highmem_longrun
preprocess__bowtie2__extract_nonhost: small,medium,large,highmem,longrun,highmem_longrun
preprocess__bowtie2__extract_nonhost_run: large,highmem,longrun,highmem_longrun
preprocess__bowtie2__map: medium,large,highmem,longrun,highmem_longrun
preprocess__fastp__run: medium,large
preprocess__samtools__stats_cram: small, medium, large
preprocess__store_final_fastq: small,medium,large,highmem,longrun,highmem_longrun

quantify__bowtie2__build: small, medium,large
quantify__bowtie2__map: medium,large,highmem,longrun,highmem_longrun
quantify__coverm__contig_aggregate: small, medium,large
quantify__coverm__contig_one: small, medium,large
quantify__coverm__genome_aggregate: small, medium,large
quantify__coverm__genome_run: small, medium,large
quantify__samtools__stats_cram: small, medium,large

read_annotate__diamond__assign: medium_nvme,large_nvme,highmem,longrun,highmem_longrun
read_annotate__diamond__summarise: small,medium,large
read_annotate__humann__run: medium,large,highmem,longrun,highmem_longrun
read_annotate__humann_condense: small, medium, large
read_annotate__kraken2__assign: full_node      # The full_node setting is for the /dev/shm ramdisc speedup. If you have nvme discs, better pick a set with those
read_annotate__krona__visualize: medium,large
read_annotate__metaphlan__condense: small, medium, large
read_annotate__metaphlan__run: medium,large
read_annotate__nonpareil__aggregate: small, medium,large
read_annotate__nonpareil__run: medium,large
read_annotate__phyloflash__condense: small, medium,large
read_annotate__phyloflash__run: medium,large
read_annotate__singlem__condense: small, medium, large
read_annotate__singlem__microbial_fraction: small, medium, large
read_annotate__singlem__pipe: small, medium, large
read_annotate__singlem__aggregate_microbial_fraction: small, medium,large
read_annotate__sylph_profile: medium, large

reference__hosts__recompress: small,medium,large

report__preprocess: small,medium,large
report__reads: small,medium,large
report__sample__multiqc: small,medium,large
report__step__reads: small,medium,large
report__step__preprocess: small,medium,large
report__step__assemble: small,medium,large
report__step__quantify: small,medium,large

test_error: small,medium,large