# Paths and parameters relative to references
---
hosts:  # Add more in case of multi-host, remove entries in case of environmental sample
  bovine: resources/reference/Bos_taurus.ARS-UCD1.3.dna.toplevel.fa.gz
  human: resources/reference/Homo_sapiens.GRCh38.dna.toplevel.fa.gz
  #ciliates: resources/reference/Ciliates_20240528.fa.gz
  ryegrass: resources/reference/Lolium_perenne.MPB_Lper_Kyuss_1697.dna.toplevel.fa.gz
  sheep: resources/reference/Ovis_aries.Oar_v3.1.dna_rm.toplevel.fa.gz
  wheat: resources/reference/Triticum_aestivum.IWGSC.dna_rm.toplevel.fa.gz
  maize: resources/reference/Zea_mays.Zm-B73-REFERENCE-NAM-5.0.dna.toplevel.fa.gz
  
magscot:
  pfam_hmm: resources/MAGScoT/hmm/gtdbtk_rel207_Pfam-A.hmm.gz
  tigr_hmm: resources/MAGScoT/hmm/gtdbtk_rel207_tigrfam.hmm.gz

databases:
  bakta: resources/databases/bakta/db
  camper: resources/databases/camper
  checkm2: resources/databases/checkm2/CheckM2_database/uniref100.KO.1.dmnd
  diamond: # add entries as necessary, intended by two spaces
    cazy: resources/databases/diamond/CAZyDB.07142024.dmnd
  diamond_contig_protein:
    hyddb: resources/databases/diamond/hyddb.20251125.dmnd 
  dram: resources/databases/dram/20240524/
  eggnog: resources/databases/eggnog/
  eggnog7: resources/databases/eggnog7/eggnog7_20251223
  gtdbtk: resources/databases/gtdbtk/release220
  hmmer:
    #hyddb: resources/databases/hyddb/HydDB_all_MM2022.hmm
    fe: resources/databases/hyddb/Fe_only-HydDB_MM2022.hmm
    fefe: resources/databases/hyddb/FeFe-HydDB_MM2022.hmm
    nife: resources/databases/hyddb/NiFe-HydDB_MM2022.hmm
  humann_nt_dbs: resources/databases/humann/chocophlan
  humann_prot_dbs: resources/databases/humann/uniref
  kraken2:  # add entries as necessary, intended by two spaces
    # refseq500: resources/databases/kraken2/kraken2_RefSeqV205_Complete_500GB # This db requires about 1.4TB of RAM
    standard: resources/databases/kraken2/kraken2_Standard_20240112  # This db requires about 140GB of RAM
  krona: resources/databases/krona
  metaphlan4: resources/databases/metaphlan4/
  phyloflash: resources/databases/phyloflash/138.2
  phylophlan: # add entries as necessary, intended by two spaces
    amphora2: resources/databases/phylophlan/amphora2
    phylophlan: resources/databases/phylophlan/phylophlan
  singlem: resources/databases/singlem/S4.3.0.GTDB_r220.metapackage_20240523.smpkg.zb
  sylph: resources/databases/sylph/gtdb-r220-c200-dbv1.syldb
  virify: resources/databases/virify
